repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--scopes, "fpfind,fpplot,freqcd,freqservo,parser", feat, fix, perf, refactor, style, test, docs, build]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.1
    hooks:
      - id: ruff
        args: [ --fix ]
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]
