[lint]
# Choose from list of rules: <https://docs.astral.sh/ruff/rules/>
select = [
    "E", "W",  # PEP8 code styles
    "I",       # isort
    "F",       # pyflakes
    "PL",      # pylint
    "Q",       # flake8-quotes
    "C90",     # code complexity
]
ignore = [
    "PLR2004",  # magic constants
    "PLW2901",  # override for-loop assignments
    "PLR0913",  # large number of arguments
    "C901",     # complex methods
]

[lint.per-file-ignores]
# Ignore line length for CLI files
"src/fpfind/fpfind.py" = [
    "E501",     # line length 
    "PLR0912",  # too many branches
    "PLR0915",  # too many statements
    "PLW0603",  # global variables - needs eventual refactoring
]

