#!/bin/sh
# pre-push hook to reject commits with 'wip' categories
# Copied directly from git example.
#
# This sample shows how to prevent push of commits where the log message starts
# with "wip" (work in progress).

remote="$1"
url="$2"

zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')

while read local_ref local_oid remote_ref remote_oid
do
	if test "$local_oid" = "$zero"
	then
		# Handle delete
		:
	else
		if test "$remote_oid" = "$zero"
		then
			# New branch, examine all commits
			range="$local_oid"
		else
			# Update to existing branch, examine new commits
			range="$remote_oid..$local_oid"
		fi

		# Check for WIP commit
		commit=$(git rev-list -n 1 --grep '^wip' "$range")
		if test -n "$commit"
		then
			echo >&2 "Found 'wip' commit in $local_ref, not pushing"
			exit 1
		fi
	fi
done

exit 0
